### ISSUE TITLE
读数据并解析的逻辑不正确

### ISSUE THREAD

**Issue by ideawu** [LazyZhu/lua-resty-ssdb#2]
```
    for v in gmatch(data, "%d+\n([^\n]+)\n") do
        insert(val, v)
    end
```

很明显, 不能直接用正则这样解析, 因为数据中可能包含\n. 正确的逻辑是:
1. 解析包含数字的行, 得到len. 如果是空行, 则解析结束.
2. 将该行之后的一共len字节的数据作为数据, 添加到返回列表中.
3. 跳过 1和2 已经处理的字节数, 以及一个'\n'(并兼容\r\n), 继续回到1继续解析.

**Comment by ideawu** [comment]
而且, 也不能

```
local data_reader = sock:receiveuntil("\n\n", { inclusive = true })
```

这样读取数据也是不对的. 原因还是因为数据中包括\n\n, 正确的算法是, 尽可能读, 然后解析.

**Comment by LazyZhu** [comment]
@ ideawu 
因为ssdb的存储转义逻辑，存储的数据不可能含有\n或\n\n
没有发现存储内容为\n的方法
set key \n, get key 为 n
set key \\n, get key 为 \\n

**Comment by ideawu** [comment]
@LazyZhu Hi, 你还完全理解ssdb的网络协议. ssdb网络协议支持二进制数据.

这是正确的读取代码, 我现在github用得不熟, 麻烦你先手工合并一下吧.

```
local function _read_reply(sock)
    local val = {}

    while true do
        -- read block size
        local line, err, partial = sock:receive()
        if not line or len(line)==0 then
            -- packet end
            break
        end
        local d_len = tonumber(line)

        --local data, err, partial = sock:receive(d_len)
        local data, err, partial = sock:receive(d_len)
        insert(val, data);

        -- ignore the trailing lf/crlf after block data
        local line, err, partial = sock:receive()
    end

    local v_num = tonumber(#val)

    if v_num == 1 then
        return val
    else
        remove(val,1)
        return val
    end
end
```

**Comment by ideawu** [comment]
这是ssdb的协议定义:

```
Packet := Block+ '\n'
Block := Size '\n' Data '\n'
Size := literal_integer
Data := size_bytes_of_data
```

为什么需要 Size 呢? 就是为了把后面的 Data 当做是透明的数据, 所以可以是任意二进制数据.

比如一个telnet的例子:

```
3
get
3
key

2
ok
3
val
```

为什么"get"和"key"的前面有"3"? 那是因为表明其后的数据是3个字节.

你可以看一下我的这篇ppt中关于"协议解析"的部分, ssdb的协议是一种"带长度字段, 混合分隔符"的协议, 而不是一种单纯的"带分隔符"的协议, 所以不能用正则分隔来解析. http://www.slideshare.net/ideawu/ss-17454292

**Comment by ideawu** [comment]
@LazyZhu 已经向你发Pull Request了.

**Comment by LazyZhu** [comment]
@ideawu 
1.你还没回答我上面的问题：如何存储\n?
2.一开始，我也是采取一行一行读的
但是ssdb没有像redis对reply做标记细分，所以增加了lua-resty-ssdb的复杂度

**Comment by ideawu** [comment]
@LazyZhu 你只需要把前面telnet例子中的"key"改成"\n\n\n"(并不是视觉上的"\n\n\n", 而是内存中的3个换行)即可. 前面已经说过了, 协议中的Data可以包括任意二进制数据.

**Comment by ideawu** [comment]
```
cmd = "get"
key = "key"
val = "\n"; // 或者 val = readfile("a.jpg"), 任意的二进制数据.

data = "";
data += len(cmd) + "\n" + cmd + "\n";
data += len(key) + "\n" + key + "\n";
data += len(val) + "\n" + val + "\n";
data += "\n";

sock:send(data);
```

既可存储换行符.

**Comment by LazyZhu** [comment]
@ideawu 不行的， \n会被自动转义成n，ssdb-cli中就会这样

**Comment by LazyZhu** [comment]
ssdb-cli中
set key \n, get key为 n
set key “\n”, get key为 \\n

**Comment by ideawu** [comment]
@LazyZhu 我举的例子不是使用cli, 因为cli做了一些事情, 用于将二进制数据显示给用户, 你在cli中输入"\n", 对于cli来说, 它得到的是"\", "n"两个字符(字节), 而不是'\n'一个字符(字节). 而cli在输出时, 会将一个字符'\'转成两个字符"\". 你应该在程序里面测试刚才的例子.

**Comment by ideawu** [comment]
一定要对"内存中的数据", 和"内存中的数据在屏幕(或者广义的输出设备)上的展现"这两个概念有非常明确清晰的思路, 不然你会时不时地陷入自我混乱.

**Comment by LazyZhu** [comment]
但是很奇怪，我用原来的lua-resty-ssdb存取没问题，但是phpcleps用php存，lua-resty-ssdb取就会出现问题。 :)
可能就是出现了\n转义的问题
谢谢这个补丁 ：）

**Comment by ideawu** [comment]
你原来的测试没出现问题, 是因为你读取的数据中没有包含两个连续的换行符. 图片中可能有各种字符, 所以比较容易出现.
